name: Go

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '**.flux'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Cache Flux Build
      id: cache-flux-go
      uses: actions/cache@v3
      with:
        path: |
          flux
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-flux
        
    - name: Get Flux
      if: steps.cache-flux-go.outputs.cache-hit != 'true'
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'influxdata'
        repository: 'flux'
    - name: Compile Flux
      if: steps.cache-flux-go.outputs.cache-hit != 'true'
      run: |
        cd flux
        make
        
    - name: Build Fluxpipe
      run: |
        cd /home/runner/work/fluxpipe/fluxpipe/
        cp fluxpipe.go ./flux/examples/library/
        cd ./flux/examples/library/
        go build -o fluxpipe -ldflags="-s -w" fluxpipe.go
        ls -alFh fluxpipe
        cp fluxpipe /home/runner/work/fluxpipe/fluxpipe/fluxpipe
        
    - name: Compress Fluxpipe
      run: |
        sudo apt install -y upx
        upx fluxpipe
        
    - name: Get Time
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
        
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            fluxpipe
        tag_name: v${{ steps.time.outputs.time }}
        release_name: fluxpipe_v${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true   
