name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Get Flux
      uses: GuillaumeFalourd/clone-github-repo-action@v2
      with:
        owner: 'influxdata'
        repository: 'flux'
    - name: Compile Flux & Fluxpipe
      run: |
        cp fluxpipe.go flux/examples/library/
        cd flux
        make

    - name: Build
      run: go build -o fluxpipe -ldflags="-s -w" ./flux/examples/library/fluxpipe.go
